version: "3.3"

services:
  database:
    image: postgres
    container_name: quickpay
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=quickpay
      - POSTGRES_PASSWORD=quickpay
      - POSTGRES_DB=quickpay
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
